name: Deployment pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: cancel Previous Redundants Build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Install dependencies 
        # run: npm install --no-audit --no-fund --no-optional
        # npm ci mejora la instalacion par ci
        run: npm ci
      - name: Linter 
        run: npm run lint
      - name: Build
        run: npm run build